capi20/alaw: Use 'extern' to avoid multiple definition
The library fails to compile with gcc-11.2 as 'extern' is missing from
forward declaration of global variables.

/usr/bin/ld: faxl3.o:mISDNuser/capi20/alaw.h:7: multiple definition of `alaw2lin'; daemon.o:mISDNuser/capi20/alaw.h:7: first defined here
/usr/bin/ld: faxl3.o:mISDNuser/capi20/alaw.h:6: multiple definition of `slin2alaw'; daemon.o:mISDNuser/capi20/alaw.h:6: first defined here
/usr/bin/ld: faxl3.o:mISDNuser/capi20/alaw.h:5: multiple definition of `lin2alaw'; daemon.o:mISDNuser/capi20/alaw.h:5: first defined here
/usr/bin/ld: alaw.o:mISDNuser/capi20/alaw.h:5: multiple definition of `lin2alaw'; daemon.o:mISDNuser/capi20/alaw.h:5: first defined here
/usr/bin/ld: alaw.o:mISDNuser/capi20/alaw.h:6: multiple definition of `slin2alaw'; daemon.o:mISDNuser/capi20/alaw.h:6: first defined here
/usr/bin/ld: alaw.o:mISDNuser/capi20/alaw.h:7: multiple definition of `alaw2lin'; daemon.o:mISDNuser/capi20/alaw.h:7: first defined here